name: WakaTime Metrics
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  update-readme:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: 'False'
          SHOW_SHORT_INFO: 'False'
          SHOW_PROFILE_VIEWS: 'False'
