name: WakaTime Metrics
on:
  schedule: 
    - cron: '30 23 * * *'
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  update-readme:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: jonhoffmam/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_limit: 10
          plugin_wakatime_days: 365
          plugin_wakatime_sections: time, languages, languages-graphs, editors, editors-graphs, os, os-graphs

      - uses: jonhoffmam/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
