name: WakaTime Metrics
on:
  schedule:
    - cron: '0 0-8/4,9-22/3 * * 1-5'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: 'False'
          SHOW_SHORT_INFO: 'False'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_LINES_OF_CODE: 'True'
