name: WakaTime Metrics
on:
  schedule: 
    - cron: '30 23 * * *'
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  update-readme:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_limit: 10
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
